"""core/schemas.py — SENTRY shared Pydantic v2 data contracts.

THIS FILE IS THE SINGLE SOURCE OF TRUTH FOR ALL INTER-STAGE DATA SHAPES.
Do NOT edit this file in any stage other than P0.  If a schema appears wrong,
raise a SCHEMA CHANGE REQUEST to the P0 owner.

Import convention for all other stages:
    from core.schemas import Chunk, EvidenceReport, DiagnosisResponse, ...
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Shared base — all SENTRY models inherit from this so serialisation settings
# are applied uniformly across every stage.
# ---------------------------------------------------------------------------


class _SentryBase(BaseModel):
    """Project-wide base: strict validation, no extra fields allowed."""

    model_config = {
        # Reject payloads that contain undeclared fields; catches typos early.
        "extra": "forbid",
        # Allow datetime objects to be used directly in JSON serialisation.
        "arbitrary_types_allowed": False,
        # Populate model fields by alias so JSON round-trips work cleanly.
        "populate_by_name": True,
    }


# ===========================================================================
# SECTION 1 — INGESTION / CORPUS MODELS
# ===========================================================================


class SafetyNote(_SentryBase):
    """A single safety statement extracted verbatim from a source document.

    Severity mirrors IEC/ANSI Z535 signal words; they map directly to the
    keyword regex used in R1.3.
    """

    text: str = Field(..., description="Verbatim safety sentence from the source document.")
    severity: Literal["danger", "warning", "caution", "notice"] = Field(
        ...,
        description="Signal-word severity level per IEC/ANSI Z535.",
    )


class Chunk(_SentryBase):
    """A retrievable document fragment produced by the S1 ingestion pipeline.

    chunk_id is deterministic: sha1(doc_id + section_path + chunk_index)[:12],
    so citations never rot when a document is re-ingested unchanged (R1.5).
    """

    chunk_id: str = Field(..., description="Deterministic 12-hex-char SHA-1 prefix.")
    doc_id: str = Field(..., description="Stable document identifier (slug, not a path).")
    doc_title: str = Field(..., description="Human-readable document title.")
    revision: str = Field(..., description='E.g. "Rev C, 2023-08".')
    section_path: list[str] = Field(
        ...,
        description="Ordered heading breadcrumb, outermost first.",
    )
    page_start: int = Field(..., ge=1, description="1-indexed starting page.")
    page_end: int = Field(..., ge=1, description="1-indexed ending page (inclusive).")
    text: str = Field(..., description="Raw extracted text of this chunk.")
    chunk_type: Literal["procedure", "description", "table", "warning"] = Field(
        ..., description="Structural classification used to weight retrieval."
    )
    has_safety: bool = Field(
        ..., description="True iff at least one SafetyNote was found in this chunk."
    )
    safety_notes: list[SafetyNote] = Field(
        default_factory=list,
        description="Verbatim safety sentences extracted from this chunk (R1.3).",
    )
    asset_class: str = Field(
        ..., description='Equipment class, e.g. "centrifugal_pump".'
    )
    applicable_models: list[str] = Field(
        default_factory=list,
        description="Model numbers this chunk applies to, e.g. [\"CP-450\", \"CP-460\"].",
    )
    token_count: int = Field(..., ge=0, description="Approximate token count for budget tracking.")


class ErrorCodeEntry(_SentryBase):
    """Structured row from the error-code side-table extracted during ingestion (R1.4).

    Looked up by exact match, never by fuzzy retrieval, to avoid hallucinated meanings.
    """

    code: str = Field(..., description='Machine error code, e.g. "E-204".')
    asset_class: str = Field(..., description="Equipment class this code applies to.")
    meaning: str = Field(..., description="Human-readable short description of the fault.")
    probable_causes: list[str] = Field(
        default_factory=list,
        description="Ordered list of probable causes from the OEM table.",
    )
    section_ref: str = Field(
        ...,
        description="Section heading or chunk_id where the error code is defined.",
    )


# ===========================================================================
# SECTION 2 — EVIDENCE MODELS  (S2 output contract)
# ===========================================================================


class SensorReading(_SentryBase):
    """A single raw sensor value as supplied in the /v1/diagnose request payload."""

    name: str = Field(..., description="Sensor identifier matching the asset's baseline config.")
    value: float = Field(..., description="Measured value in the reported unit.")
    unit: str = Field(..., description='Physical unit string, e.g. "C", "mm/s", "bar".')
    status: Literal["ok", "missing", "stale"] = Field(
        default="ok",
        description="Data-quality flag; stale means outside the freshness window (R2.8).",
    )
    last_seen: datetime | None = Field(
        default=None,
        description="UTC timestamp of the reading; None only when status=='missing'.",
    )


class Deviation(_SentryBase):
    """Quantified deviation for one sensor, as computed by the S2 Evidence Engine.

    All numeric fields are computed deterministically by S2 — the LLM never
    touches these values (R2.3, R5.2).
    """

    sensor: str = Field(..., description="Sensor identifier.")
    value: float = Field(..., description="Measured value.")
    unit: str = Field(..., description="Physical unit.")
    nominal: float = Field(..., description="Nominal (expected) value from the baseline config.")
    normal_range: tuple[float, float] = Field(
        ..., description="[low, high] bounds of the normal operating band."
    )
    delta: float = Field(..., description="value − nominal; signed.")
    pct_dev: float = Field(..., description="delta / nominal; signed fraction.")
    z_score: float = Field(..., description="Standard-score (robust MAD variant for vibration).")
    band: Literal["normal", "warn", "alarm", "out_of_range"] = Field(
        ..., description="Operating band classification (R2.3)."
    )
    severity: float = Field(
        ..., ge=0, le=100, description="Severity score 0-100, monotonic in |z| and band (R2.4)."
    )
    trend: Literal["rising", "falling", "stable", "unknown"] = Field(
        ..., description="Direction of recent change (EWMA slope sign)."
    )
    roc_per_min: float | None = Field(
        default=None,
        description="Rate of change per minute; None if no time series was supplied.",
    )
    source: str = Field(
        ...,
        description='Baseline provenance: "oem_config" or "learned_baseline".',
    )


class Signature(_SentryBase):
    """A cross-sensor pattern match from declarative YAML correlation rules (R2.5).

    Explicitly labelled as a heuristic hint to the retriever, never as fact.
    """

    name: str = Field(..., description='Pattern name, e.g. "bearing_distress".')
    confidence: float = Field(..., ge=0.0, le=1.0, description="Rule-computed confidence [0, 1].")
    rule_id: str = Field(..., description='Rule identifier from the YAML corpus, e.g. "R-014".')
    basis: list[str] = Field(
        ..., description="Sensor names that triggered this rule."
    )


class HistoryFeatures(_SentryBase):
    """Maintenance history features extracted for this asset (R2.7)."""

    days_since_service: int = Field(
        ..., ge=0, description="Calendar days since the last recorded service event."
    )
    same_code_90d: int = Field(
        ..., ge=0, description="Count of occurrences of the same error code in the last 90 days."
    )
    recent_parts: list[str] = Field(
        default_factory=list,
        description="Parts replaced at the last service event.",
    )


class ErrorCodeResult(_SentryBase):
    """Outcome of an exact-match error-code lookup (R2.6).

    'absent' means no error code was submitted; 'unrecognized' triggers refusal.
    """

    code: str | None = Field(default=None, description="The submitted error code, or None.")
    meaning: str | None = Field(
        default=None,
        description="OEM-defined meaning; None if unrecognized or absent.",
    )
    status: Literal["recognized", "unrecognized", "absent"] = Field(
        ..., description="Lookup result; 'unrecognized' is a refusal trigger (R2.6)."
    )


class EvidenceReport(_SentryBase):
    """Complete output of the S2 Evidence Engine for one diagnostic request.

    This is the primary input to S3 (Retrieval) and S5 (Synthesis).
    """

    asset_id: str = Field(..., description="Asset identifier from the request.")
    asset_class: str = Field(..., description='Equipment class, e.g. "centrifugal_pump".')
    captured_at: datetime = Field(..., description="Timestamp of the sensor snapshot.")
    error_code: ErrorCodeResult = Field(..., description="Error-code lookup result.")
    deviations: list[Deviation] = Field(
        default_factory=list,
        description="Sensors whose values exceed normal-band thresholds, sorted by severity desc.",
    )
    normal_sensors: list[str] = Field(
        default_factory=list,
        description="Sensor names whose readings are within the normal band.",
    )
    missing_sensors: list[str] = Field(
        default_factory=list,
        description="Sensors with status=='missing' or 'stale' (R2.8).",
    )
    signatures: list[Signature] = Field(
        default_factory=list,
        description="Cross-sensor patterns matched by correlation rules (R2.5).",
    )
    history_features: HistoryFeatures = Field(
        ..., description="Maintenance history features for this asset."
    )


# ===========================================================================
# SECTION 3 — RETRIEVAL MODELS  (S3 output contract)
# ===========================================================================


class RetrievedChunk(_SentryBase):
    """A chunk returned by the retrieval stage, decorated with scoring metadata."""

    chunk: Chunk = Field(..., description="The retrieved chunk payload.")
    sparse_score: float | None = Field(
        default=None, description="BM25 / TF-IDF score; None if sparse retrieval was skipped."
    )
    dense_score: float | None = Field(
        default=None, description="Dense embedding cosine score; None if dense retrieval was skipped."
    )
    fused_score: float | None = Field(
        default=None, description="RRF-fused score after hybrid merge; None if not applicable."
    )
    rerank_score: float | None = Field(
        default=None, description="Cross-encoder rerank score; None if reranker was not run."
    )
    retrieved_by: list[str] = Field(
        default_factory=list,
        description='Which sub-retrievers surfaced this chunk, e.g. ["sparse", "dense"].',
    )
    forced_safety_include: bool = Field(
        default=False,
        description="True iff this chunk was force-included because it contains a safety note "
        "relevant to the query (R5.5 safety sweep).",
    )


class RetrievalTrace(_SentryBase):
    """Low-level trace from a single retrieval sub-system for debugging / ablation."""

    query_text: str = Field(..., description="The query string sent to this retriever.")
    engine: str = Field(..., description='Retriever name, e.g. "bm25", "dense", "tfidf".')
    top_k: int = Field(..., ge=1, description="Number of results requested from this engine.")
    raw_results: list[tuple[str, float]] = Field(
        default_factory=list,
        description="(chunk_id, score) pairs in rank order from this engine.",
    )


class RetrievalResult(_SentryBase):
    """Complete output of the S3 Retrieval stage for one diagnostic request."""

    status: Literal["sufficient", "insufficient"] = Field(
        ...,
        description=(
            "'insufficient' triggers the refusal path in S5 (R5.6). "
            "Sufficiency is determined by whether best_score >= relevance_floor."
        ),
    )
    chunks: list[RetrievedChunk] = Field(
        default_factory=list,
        description="Final ranked list of chunks to be passed to S5.",
    )
    traces: list[RetrievalTrace] = Field(
        default_factory=list,
        description="Per-engine traces for ablation analysis and debugging.",
    )
    best_score: float = Field(
        ..., description="Highest fused (or rerank) score among the retrieved chunks."
    )


# ===========================================================================
# SECTION 4 — ANOMALY MODEL  (S4 output contract, feature-flagged)
# ===========================================================================


class AnomalyResult(_SentryBase):
    """Output from the optional S4 anomaly detection model (use_anomaly_model flag).

    When the flag is False this model is never instantiated; S5 proceeds without it.
    """

    model_version: str = Field(..., description="MLflow artifact version or semver of the model.")
    anomaly_score: float = Field(
        ..., ge=0.0, le=1.0, description="Normalised anomaly score in [0, 1]."
    )
    is_anomalous: bool = Field(..., description="True iff anomaly_score exceeds the model's threshold.")
    feature_attributions: dict[str, float] = Field(
        default_factory=dict,
        description="SHAP values keyed by sensor name; empty dict if SHAP was not run.",
    )


# ===========================================================================
# SECTION 5 — SYNTHESIS / OUTPUT MODELS  (S5 output contract)
# ===========================================================================


class Citation(_SentryBase):
    """A resolvable pointer back to a specific page in a specific document revision.

    Every citation must be validatable against the chunk store (R5.4).
    """

    chunk_id: str = Field(..., description="chunk_id of the source chunk.")
    doc_title: str = Field(..., description="Document title for display.")
    revision: str = Field(..., description="Document revision string.")
    section: str = Field(..., description="Section heading or section_path joined as a string.")
    page: int = Field(..., ge=1, description="Page number within the source document.")


class MeasuredFact(_SentryBase):
    """A single quantitative fact copied programmatically from the EvidenceReport.

    The LLM never generates these numbers; it is only permitted to reference
    pre-computed values (R5.2).
    """

    statement: str = Field(
        ...,
        description="Human-readable statement of the measured fact.",
    )
    source: str = Field(
        ...,
        description='Provenance label, e.g. "sensor_engine" or "error_code_lookup".',
    )
    sensor: str | None = Field(
        default=None,
        description="Sensor name, if the fact originates from a sensor reading.",
    )


class ManualInstruction(_SentryBase):
    """A single procedural step derived verbatim or minimally paraphrased from a document (R5.2).

    Any step where verbatim_safety==True MUST preserve the exact safety text
    from the source chunk's safety_notes (R5.5).
    """

    step: str = Field(
        ...,
        description="Instruction text; safety sentences must be verbatim substrings of source.",
    )
    verbatim_safety: bool = Field(
        ...,
        description="True iff this step contains a safety sentence that must appear verbatim.",
    )
    citation: Citation = Field(..., description="Source citation for the guardrail resolver.")


class ChecklistStep(_SentryBase):
    """One step in the ranked inspection checklist (R5.3).

    Ordering rule: safety/isolation first, then non-invasive observation, then
    low-cost checks, then invasive disassembly.  This ordering is enforced in
    post-processing, not generated by the model.
    """

    order: int = Field(..., ge=1, description="1-based position in the final ordered checklist.")
    action: str = Field(..., description="The action the technician must perform.")
    expected_observation: str = Field(
        ..., description="What a passing outcome looks like."
    )
    if_abnormal_then: str = Field(
        ..., description="Escalation or branching instruction if the observation fails."
    )
    tools_required: list[str] = Field(
        default_factory=list,
        description="Tools and PPE needed for this step.",
    )
    est_minutes: int = Field(..., ge=0, description="Estimated elapsed time in minutes.")
    is_safety_critical: bool = Field(
        ..., description="True iff this step involves energy isolation, LOTO, or PPE."
    )
    citation: Citation = Field(..., description="Mandatory resolvable citation (R5.4).")


class Hypothesis(_SentryBase):
    """One ranked probable root cause produced by S5 (R5.2, R5.10).

    Confidence buckets are derived from retrieval scores + deviation severity
    in code, not freely generated by the LLM.
    """

    rank: int = Field(..., ge=1, description="Ordinal rank; 1 = most probable.")
    cause: str = Field(..., description="Human-readable description of the probable cause.")
    confidence: Literal["high", "medium", "low"] = Field(
        ..., description="Bucket derived from rerank score + deviation severity (R5.10)."
    )
    confidence_score: float = Field(
        ..., ge=0.0, le=1.0, description="Numeric confidence used to compute the bucket."
    )
    supporting_sensors: list[str] = Field(
        default_factory=list,
        description="Sensor names whose deviations support this hypothesis.",
    )
    supporting_chunks: list[str] = Field(
        default_factory=list,
        description="chunk_ids whose content supports this hypothesis.",
    )
    discriminating_check: str = Field(
        ...,
        description="The single test or observation that would confirm or refute this hypothesis.",
    )


class Refusal(_SentryBase):
    """Structured refusal payload emitted when SENTRY cannot safely answer (R5.6).

    A refusal is not an error; it is a safety-correct outcome that tells the
    technician exactly what the system could not do and what to do instead.
    """

    reason: Literal[
        "no_relevant_evidence",
        "unrecognized_code",
        "guardrail_block",
        "schema_failure",
    ] = Field(..., description="Machine-readable cause for downstream routing.")
    message: str = Field(..., description="Human-readable explanation shown to the technician.")
    suggested_action: str = Field(
        ..., description="Escalation guidance, e.g. consult OEM or contact reliability engineer."
    )


class GuardrailReport(_SentryBase):
    """Summary of all guardrail checks run against a synthesis response (R5.4, R5.5, R5.9)."""

    passed: list[str] = Field(
        default_factory=list,
        description='Names of guardrails that passed, e.g. ["citation", "safety", "numeric"].',
    )
    failed: list[str] = Field(
        default_factory=list,
        description="Names of guardrails that failed; non-empty triggers a block or refusal.",
    )
    dropped_steps: int = Field(
        default=0,
        ge=0,
        description="Number of checklist steps dropped due to failed citation resolution (R5.4).",
    )
    notes: str = Field(
        default="",
        description="Free-text diagnostic notes from the guardrail layer for the audit log.",
    )


class ResponseMeta(_SentryBase):
    """Telemetry and provenance metadata attached to every DiagnosisResponse."""

    prompt_version: str = Field(..., description='Prompt file version tag, e.g. "v1.4.0".')
    model: str = Field(..., description="LLM model identifier as reported by the provider.")
    retriever: str = Field(
        ..., description='Retrieval configuration used, e.g. "hybrid+rerank".'
    )
    chunks_retrieved: int = Field(
        ..., ge=0, description="Number of chunks passed to the LLM context window."
    )
    latency_ms: int = Field(..., ge=0, description="End-to-end wall-clock latency in milliseconds.")
    corpus_revision: str = Field(
        ..., description="Git revision or DVC hash of the corpus at the time of retrieval."
    )


class DiagnosisResponse(_SentryBase):
    """Complete structured output of the SENTRY pipeline for one diagnostic request.

    This is the contract produced by S5 (Synthesis) and consumed by S6 (API)
    and S7 (UI).  Every field must be present; refusal is represented by a
    non-None `refusal` field, not by omitting other fields.
    """

    request_id: str = Field(..., description="Unique request identifier (ULID or UUID).")
    asset_id: str = Field(..., description="Asset identifier echoed from the request.")
    measured_facts: list[MeasuredFact] = Field(
        default_factory=list,
        description="Verbatim quantitative facts from S2; never generated by the LLM.",
    )
    manual_instructions: list[ManualInstruction] = Field(
        default_factory=list,
        description="Cited procedural steps derived from retrieved document chunks.",
    )
    inspection_checklist: list[ChecklistStep] = Field(
        default_factory=list,
        description="Ordered checklist; safety/isolation steps sort to the front in post-processing.",
    )
    hypotheses: list[Hypothesis] = Field(
        default_factory=list,
        description="Ranked probable root causes; explicitly labelled as uncertain.",
    )
    retrieval_status: Literal["sufficient", "insufficient"] = Field(
        ..., description="Echoed from RetrievalResult; 'insufficient' implies a refusal."
    )
    refusal: Refusal | None = Field(
        default=None,
        description="Populated iff the system could not produce a grounded response (R5.6).",
    )
    guardrails: GuardrailReport = Field(
        ..., description="Guardrail check outcomes for this response."
    )
    meta: ResponseMeta = Field(..., description="Telemetry and provenance for the audit log.")


# ===========================================================================
# SECTION 6 — API I/O MODELS  (S6 request/response wire shapes)
# ===========================================================================


class DiagnoseRequest(_SentryBase):
    """Incoming payload for POST /v1/diagnose.

    Sensors are keyed by sensor name; missing keys mean the sensor was not
    supplied (which is distinct from status=='missing' inside a SensorReading).
    """

    asset_id: str = Field(..., description="Asset identifier (must match a known asset).")
    captured_at: datetime = Field(
        ..., description="ISO-8601 timestamp of the sensor snapshot."
    )
    error_code: str | None = Field(
        default=None,
        description="Machine error code displayed on the HMI, if present.",
    )
    sensors: dict[str, SensorReading] = Field(
        default_factory=dict,
        description="Sensor readings keyed by sensor name.",
    )
    context: dict[str, object] = Field(
        default_factory=dict,
        description="Free-form key-value pairs from the request context (operating hours, notes, etc.).",
    )


class FeedbackRequest(_SentryBase):
    """Payload for POST /v1/feedback — stretch goal (R13 feedback loop).

    Records which checklist step resolved the fault, for reranker training data.
    """

    request_id: str = Field(..., description="The request_id of the DiagnosisResponse being rated.")
    resolved_at_step: int | None = Field(
        default=None,
        ge=1,
        description="order of the ChecklistStep that resolved the fault; None if unresolved.",
    )
    was_resolved: bool = Field(
        ..., description="True iff the fault was resolved during this diagnosis session."
    )
    comments: str = Field(
        default="",
        description="Optional free-text from the technician.",
    )
