"""synthesis/compose.py — Orchestrate S5 Synthesis pipeline into DiagnosisResponse.

Hard constraints:
- Refusal path taken with ZERO LLM calls if retrieval is insufficient or error code
  is unrecognized with no deviation-matched section.
- measured_facts are built in code, never generated by LLM.
- checklist ordering is enforced in code (safety steps first).
- hypothesis confidence is calibrated in code.
- Populates ResponseMeta with prompt_version and corpus_revision.
- Output validates strictly against DiagnosisResponse schema.
"""

from __future__ import annotations

import pathlib
import time
import uuid
from collections.abc import Callable
from typing import Any

import structlog

from core.config import settings
from core.errors import RefusalRequired
from core.schemas import (
    DiagnosisResponse,
    EvidenceReport,
    GuardrailReport,
    Hypothesis,
    Refusal,
    ResponseMeta,
    RetrievalResult,
)
from synthesis.confidence import calibrate_hypotheses
from synthesis.facts import build_measured_facts, format_facts_for_prompt
from synthesis.llm import generate_synthesis_draft
from synthesis.ordering import order_checklist_steps

logger = structlog.get_logger(__name__)

_PROMPTS_DIR = pathlib.Path(__file__).parent / "prompts"
_DEFAULT_PROMPT_VERSION = "v1.0.0"


def load_system_prompt() -> str:
    """Load the immutable system prompt containing hard rules."""
    path = _PROMPTS_DIR / "system_v1.txt"
    return path.read_text(encoding="utf-8")


def load_user_template() -> str:
    """Load the user prompt template."""
    path = _PROMPTS_DIR / "user_template_v1.txt"
    return path.read_text(encoding="utf-8")


def format_retrieved_documents(retrieval: RetrievalResult) -> str:
    """Format retrieved chunks inside delimited untrusted reference blocks.

    Carries chunk_id, document title, revision, section, page, and verbatim safety notes.
    """
    if not retrieval.chunks:
        return "No manual chunks retrieved."

    blocks: list[str] = []
    for rc in retrieval.chunks:
        c = rc.chunk
        section_str = " > ".join(c.section_path) if c.section_path else "General"
        header = f"[chunk_id: {c.chunk_id} | {c.doc_title} {c.revision} | §{section_str} | p.{c.page_start}]"

        lines = [header]
        for note in c.safety_notes:
            lines.append(f"SAFETY: {note.severity.upper()}: {note.text}")
        lines.append(c.text)
        blocks.append("\n".join(lines))

    return "\n\n---\n\n".join(blocks)


def format_user_prompt(evidence: EvidenceReport, retrieval: RetrievalResult) -> str:
    """Interpolate EvidenceReport and RetrievalResult into user_template_v1.txt."""
    facts = build_measured_facts(evidence)
    facts_text = format_facts_for_prompt(facts)

    err = evidence.error_code
    if err.code:
        err_info = f"{err.code} ({err.status}): {err.meaning or 'Unknown'}"
    else:
        err_info = "None active"

    recent_parts = ", ".join(evidence.history_features.recent_parts) if evidence.history_features.recent_parts else "None"
    signatures_text = (
        ", ".join(f"{s.name} (conf={s.confidence:.2f})" for s in evidence.signatures)
        if evidence.signatures
        else "None detected"
    )

    docs_text = format_retrieved_documents(retrieval)

    template = load_user_template()
    return template.format(
        measured_facts=facts_text,
        asset_id=evidence.asset_id,
        asset_class=evidence.asset_class,
        days_since_service=evidence.history_features.days_since_service,
        error_code_info=err_info,
        recent_parts=recent_parts,
        signatures=signatures_text,
        retrieved_documents=docs_text,
    )


def _build_unverified_refusal_hypotheses(
    evidence: EvidenceReport,
) -> list[Hypothesis]:
    """Generate explicitly unverified hypotheses when refusing due to missing manual evidence."""
    hypotheses: list[Hypothesis] = []

    if evidence.signatures:
        for idx, sig in enumerate(evidence.signatures[:2], start=1):
            hypotheses.append(
                Hypothesis(
                    rank=idx,
                    cause=f"Potential {sig.name.replace('_', ' ')} (unverified: manual procedure unavailable)",
                    confidence="low",
                    confidence_score=round(min(0.35, sig.confidence * 0.4), 2),
                    supporting_sensors=sig.basis,
                    supporting_chunks=[],
                    discriminating_check="Inspect physical asset directly and check OEM documentation.",
                )
            )
    elif evidence.deviations:
        top_devs = evidence.deviations[:2]
        hypotheses.append(
            Hypothesis(
                rank=1,
                cause=f"Abnormal operating state on {', '.join(d.sensor for d in top_devs)} (unverified: no matching manual section)",
                confidence="low",
                confidence_score=0.20,
                supporting_sensors=[d.sensor for d in top_devs],
                supporting_chunks=[],
                discriminating_check="Verify sensor calibration and perform physical inspection.",
            )
        )
    else:
        code_str = evidence.error_code.code or "unknown"
        hypotheses.append(
            Hypothesis(
                rank=1,
                cause=f"Unrecognized machine fault code {code_str} (unverified: documentation missing)",
                confidence="low",
                confidence_score=0.10,
                supporting_sensors=[],
                supporting_chunks=[],
                discriminating_check="Check HMI fault logs and contact OEM representative.",
            )
        )

    return hypotheses


def build_refusal_response(
    evidence: EvidenceReport,
    retrieval: RetrievalResult,
    *,
    reason: str,
    message: str,
    suggested_action: str,
    request_id: str,
    prompt_version: str,
    corpus_revision: str,
    latency_ms: int = 0,
    model_name: str = "none",
) -> DiagnosisResponse:
    """Build a compliant DiagnosisResponse representing the refusal path."""
    measured_facts = build_measured_facts(evidence)
    unverified_hypotheses = _build_unverified_refusal_hypotheses(evidence)

    retriever_label = (
        f"{settings.retriever}+rerank" if settings.use_reranker else settings.retriever
    )

    return DiagnosisResponse(
        request_id=request_id,
        asset_id=evidence.asset_id,
        measured_facts=measured_facts,
        manual_instructions=[],
        inspection_checklist=[],
        hypotheses=unverified_hypotheses,
        retrieval_status=retrieval.status,
        refusal=Refusal(
            reason=reason,  # type: ignore[arg-type]
            message=message,
            suggested_action=suggested_action,
        ),
        guardrails=GuardrailReport(
            passed=[],
            failed=[],
            dropped_steps=0,
            notes="Refusal path executed. Procedural steps withheld.",
        ),
        meta=ResponseMeta(
            prompt_version=prompt_version,
            model=model_name,
            retriever=retriever_label,
            chunks_retrieved=len(retrieval.chunks),
            latency_ms=latency_ms,
            corpus_revision=corpus_revision,
        ),
    )


def synthesize(
    evidence: EvidenceReport,
    retrieval: RetrievalResult,
    *,
    request_id: str | None = None,
    prompt_version: str = _DEFAULT_PROMPT_VERSION,
    corpus_revision: str = "v1.0",
    client: Any = None,
    custom_invoker: Callable[[str, str], Any] | None = None,
) -> DiagnosisResponse:
    """Synthesize evidence and retrieval results into a DiagnosisResponse.

    Refusal Short-Circuit:
      If retrieval is 'insufficient' OR error code is unrecognized with no
      deviation-matched section, takes the refusal path immediately with 0 LLM calls.
    """
    start_time = time.perf_counter()
    req_id = request_id or f"req_{uuid.uuid4().hex[:10]}"

    # --- REFUSAL SHORT-CIRCUIT 1: Insufficient retrieval ---
    if retrieval.status == "insufficient":
        logger.info("synthesize_refusal_insufficient_retrieval", asset_id=evidence.asset_id)
        latency_ms = int((time.perf_counter() - start_time) * 1000)
        return build_refusal_response(
            evidence,
            retrieval,
            reason="no_relevant_evidence",
            message="Retrieved manual sections do not meet the relevance floor for this machine state.",
            suggested_action="Consult original equipment manufacturer documentation or facility engineering.",
            request_id=req_id,
            prompt_version=prompt_version,
            corpus_revision=corpus_revision,
            latency_ms=latency_ms,
        )

    # --- REFUSAL SHORT-CIRCUIT 2: Unrecognized error code without deviation-matched section ---
    is_unrecognized_code = evidence.error_code.status == "unrecognized"
    has_no_deviations = len(evidence.deviations) == 0
    if is_unrecognized_code and (has_no_deviations or not retrieval.chunks):
        logger.info("synthesize_refusal_unrecognized_error_code", code=evidence.error_code.code)
        latency_ms = int((time.perf_counter() - start_time) * 1000)
        code_val = evidence.error_code.code or "unknown"
        return build_refusal_response(
            evidence,
            retrieval,
            reason="unrecognized_code",
            message=f"Error code '{code_val}' is unrecognized in the asset manual and no governing section was found.",
            suggested_action="Verify code on HMI panel and consult OEM technical support.",
            request_id=req_id,
            prompt_version=prompt_version,
            corpus_revision=corpus_revision,
            latency_ms=latency_ms,
        )

    # --- LLM SYNTHESIS INVOCATION ---
    system_prompt = load_system_prompt()
    user_prompt = format_user_prompt(evidence, retrieval)

    try:
        draft, model_used = generate_synthesis_draft(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            client=client,
            custom_invoker=custom_invoker,
        )
    except RefusalRequired as exc:
        logger.warning("synthesize_refusal_from_schema_failure", error=str(exc))
        latency_ms = int((time.perf_counter() - start_time) * 1000)
        return build_refusal_response(
            evidence,
            retrieval,
            reason=exc.reason,
            message=str(exc),
            suggested_action=exc.suggested_action,
            request_id=req_id,
            prompt_version=prompt_version,
            corpus_revision=corpus_revision,
            latency_ms=latency_ms,
            model_name="schema_validation_failed",
        )

    latency_ms = int((time.perf_counter() - start_time) * 1000)

    # Check if model requested a refusal because docs didn't support procedure
    if draft.refusal_reason:
        return build_refusal_response(
            evidence,
            retrieval,
            reason=draft.refusal_reason,
            message=draft.refusal_message or "Retrieved documentation does not support an inspection procedure.",
            suggested_action=draft.refusal_suggested_action or "Consult OEM technical support.",
            request_id=req_id,
            prompt_version=prompt_version,
            corpus_revision=corpus_revision,
            latency_ms=latency_ms,
            model_name=model_used,
        )

    # In-code Fact Rendering
    measured_facts = build_measured_facts(evidence)

    # In-code Checklist Ordering (Safety steps first)
    ordered_checklist = order_checklist_steps(draft.inspection_checklist)

    # Convert LLM hypotheses to Hypothesis models with in-code calibrated confidence
    raw_hypotheses: list[Hypothesis] = []
    for h in draft.hypotheses:
        raw_hypotheses.append(
            Hypothesis(
                rank=h.rank,
                cause=h.cause,
                confidence="low",  # temporary placeholder; calibrated below
                confidence_score=0.0,
                supporting_sensors=h.supporting_sensors,
                supporting_chunks=h.supporting_chunks,
                discriminating_check=h.discriminating_check,
            )
        )
    calibrated_hypotheses = calibrate_hypotheses(raw_hypotheses, evidence, retrieval)

    retriever_label = (
        f"{settings.retriever}+rerank" if settings.use_reranker else settings.retriever
    )

    return DiagnosisResponse(
        request_id=req_id,
        asset_id=evidence.asset_id,
        measured_facts=measured_facts,
        manual_instructions=draft.manual_instructions,
        inspection_checklist=ordered_checklist,
        hypotheses=calibrated_hypotheses,
        retrieval_status=retrieval.status,
        refusal=None,
        guardrails=GuardrailReport(
            passed=[],
            failed=[],
            dropped_steps=0,
            notes="Pre-guardrail synthesis complete; emitted for S6 validation.",
        ),
        meta=ResponseMeta(
            prompt_version=prompt_version,
            model=model_used,
            retriever=retriever_label,
            chunks_retrieved=len(retrieval.chunks),
            latency_ms=latency_ms,
            corpus_revision=corpus_revision,
        ),
    )
